name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  brakeman:
    runs-on: windows-latest 
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3.7
          bundler-cache: true

      - name: Configurar Bundler
        run: bundle install

      - name: Recriar binário do Brakeman
        run: |
          rm -rf bin/brakeman
          bundle binstubs brakeman --path=bin
          chmod +x bin/brakeman

      - name: Rodar Brakeman
        run: bundle exec brakeman --no-pager